[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production" 